language: ruby

script:
- bundle exec jekyll build
- tar czf website.tar.gz -C _site/ .

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_key_id: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    local_dir: ./_site
    skip_cleanup: true
    on:
      tags: true


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
