language: ruby

script:
- bundle exec jekyll build

before_deploy:
- tar czf website.tar.gz -C _site/ .
- git config --local user.name "Mozilla Lockbox"
- git config --local user.email "lockbox@mozilla.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: website.tar.gz
  skip_cleanup: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
